# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - ../../base

# patches:
#   - path: patch-deployment.yaml
#   - path: patch-ingress.yaml

# namespace: dev

# images:
#   - name: ayoobki/maven-app
#     newTag: dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - bluegreen/
