apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

resources:
  - ../../../base

resources:
  - rollout-canary.yaml
  - destination-rule.yaml
  - virtual-service.yaml
  - istio-ingress.yaml

patches:
  - path: rollout-canary.yaml
    target:
      kind: Deployment
      name: maven-app
