apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

resources:
  - ../../../base
  - rollout-canary.yaml
  - destination-rule.yaml
  - virtual-service.yaml
  - istio-ingress.yaml

images:
  - name: ayoobki/maven-app
    newTag: stage
