apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/hpa.yaml

patches:
  - istio-canary/rollout-canary.yaml
  - istio-canary/destination-rule.yaml
  - istio-canary/virtual-service.yaml
  - istio-canary/istio-ingress.yaml

images:
  - name: ayoobki/maven-app
    newTag: stage
