apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app
          image: ayoobki/maven-app:prod
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"