apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maven-app-ingress
  namespace: dev
spec:
  rules:
    - host: dev.maven-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maven-app-active
                port:
                  number: 80
