apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: maven-app
  template:
    spec:
      containers:
        - name: maven-app
          image: ayoobki/maven-app:stage
          resources:
            requests:
              cpu: "250m"
              memory: "256mi"
            limits:
              cpu: "500m"
              memory: "512mi"