apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app
          image: ayoobki/maven-app:stage
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"